### PR TITLE
17 token expiration

### LINKED ISSUE #17: Token expiration
**Package+Version:**
Latest

**Describe the bug**
In contrast to the app this is based on, tokens expire.

**To Reproduce**
Wait around for a while, try to upload a file.

**Expected behavior**
Upload should work.

**Additional context**
These tokens probably have a refresh mechanism if they're expired.
See if that's available

### PR DESCRIPTION
**Pull request by Marvin-Brouwer**
- Added token refresh mechanism
- Corrected some dialog styles
- Added key bindings to dialogs (esc + enter)

I did the token refresh only on expiration to make the app quicker.

### CODE REVIEW

**Comment by Marvin-Brouwer** [comment]
@aseemsahoo You want to review this one?

**Comment by aseemsahoo** [comment]
> @aseemsahoo You want to review this one?

Sure! I'll review this PR certainly.

**Comment by Marvin-Brouwer** [comment]
@aseemsahoo do you have an indication of when you may have time to do the review?

**Comment by Marvin-Brouwer** [comment]
Review took too long, merging anyway.

**Pull request merged**
